# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PORT: ${{secrets.PORT}}
  PORT_TEST: ${{secrets.PORT_TEST}}
  CLOUD_NAME: ${{secrets.CLOUD_NAME}}
  API_KEY: ${{secrets.API_KEY}}
  API_SECRET: ${{secrets.API_SECRET}}
  MONGO_URL_TEST: ${{secrets.MONGO_URL_TEST}}
  JWT_SECRET: ${{secrets.JWT_SECRET}}
  JWT_EXPIRES_IN: ${{secrets.JWT_EXPIRES_IN}}
  MONGO_URL: ${{secrets.MONGO_URL}}
  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "21.x"

      - name: Install Dependencies
        run: npm install

      - name: Coveralls Report
        uses: coverallsapp/github-action@v2.2.3
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

      - name: Run tests
        run: npm run coveralls
