# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  PORT: ${{secrets.PORT}}
  PORT_TEST: ${{secrets.PORT_TEST}}
  CLOUDINARY_CLOUD_NAME: ${{secrets.CLOUDINARY_CLOUD_NAME}}
  CLOUDINARY_API_KEY: ${{secrets.CLOUDINARY_API_KEY}}
  CLOUDINARY_API_SECRET: ${{secrets.CLOUDINARY_API_SECRET}}
  ADMIN_NAME: ${{secrets.ADMIN_NAME}}
  ADMIN_PASSWORD: ${{secrets.ADMIN_PASSWORD}}
  ADMIN_NAME_TEST: ${{secrets.ADMIN_NAME_TEST}}
  ADMIN_PASSWORD_TEST: ${{secrets.ADMIN_PASSWORD_TEST}}
  SECRETKEY: ${{secrets.SECRETKEY}}
  ADMIN_USERNAME_LOGIN: ${{secrets.ADMIN_USERNAME_LOGIN}}
  ADMIN_PASSWORD_LOGIN: ${{secrets.ADMIN_PASSWORD_LOGIN}}

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "21.x"

      - name: Install Dependencies
        run: npm install

      - name: Coveralls Report
        uses: coverallsapp/github-action@v2.2.3
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

      - name: Run tests
        run: npm run coveralls
